name: RTUCommandControl
version: '${version}'
main: com.github.ipecter.rtu.commandcontrol.RTUCommandControl
api-version: 1.14
softdepend: [ PlaceholderAPI ]
authors: [ IPECTER (이팩터) ]
description: RTU PLUGINS - Controling Available Command, TabComletion Plugin
website: https://github.com/IPECTER/RTUCommandControl
libraries:
  - net.kyori:adventure-platform-bukkit:4.3.0
  - net.kyori:adventure-text-minimessage:4.13.0
commands:
  rtucc:
    usage: /rtucc reload
    description: /rtucc reload
permissions:
  rtucc.bypass.send:
    description: Command TabComplete
  rtucc.bypass.preprocess:
    description: Command Process
  rtucc.reload:
    description: Plugin reload
    default: op
  rtucc.default:
    default: true